apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IONOSCloudMachineTemplate
metadata:
  name: ionoscloud-local-matthias-worker
spec:
  template:
    spec:
      cores: 2
      ram: 4096
      cpuFamily: "INTEL_SKYLAKE"
      bootVolume:
        image: "b41c6ff3-5067-11ee-ab79-56968c86e4b4"
        type: "HDD"
        size: "25"
