apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ionoscloudcluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.25.224.0/19
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ionoscloudcluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: IONOSCloudCluster
    name: ionoscloudcluster
