apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IONOSCloudCluster
metadata:
  name: ionoscloudcluster
spec:
  location: "de/txl"
  identityName: ionos-identity
  controlPlaneEndpoint:
    host: "85.215.201.63"
    port: 6443
  lans:
    - name: private
      public: false
    - name: public
      public: true
    - name: internet
      public: true
      failoverGroups:
        - id: 3682d039-e520-4837-810c-c43358949463
  loadBalancer:
    listenerLanRef:
      name: public
    targetLanRef:
      name: private
