apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IONOSCloudMachineTemplate
metadata:
  name: ionoscloudcluster-worker
spec:
  template:
    spec:
      cores: 2
      ram: 2048
      cpuFamily: "INTEL_SKYLAKE"
      bootVolume:
        image: "3c2a7c7a-8488-11ee-811f-826459b45e91"
        type: "HDD"
        size: "25"
      nics:
        - lanRef:
            name: internet
        - lanRef:
            name: private
