apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ionoscloudcluster-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: unix:///var/run/containerd/containerd.sock
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{ ds.meta_data.hostname }}'
      files:
        - content: |
            {
              "datacenter-id": "{{ ds.meta_data.datacenter_id }}"
            }
          owner: root:root
          path: /etc/ie-csi/cfg.json
          permissions: '0644'
        - path: /tmp/init.sh
          content: |
            #!/bin/bash
            hostnamectl set-hostname "{{ ds.meta_data.hostname }}"
            echo "::1         ipv6-localhost ipv6-loopback" > /etc/hosts
            echo "127.0.0.1   localhost" >> /etc/hosts
            echo "127.0.0.1   {{ ds.meta_data.hostname }}" >> /etc/hosts
            echo "{{ ds.meta_data.hostname }}" > /etc/hostname
          owner: root:root
          permissions: '0777'
      preKubeadmCommands:
        - /tmp/init.sh > /tmp/initlog