apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ionoscloudcluster
  name: ionoscloudcluster-md-0
  namespace: default
spec:
  clusterName: ionoscloudcluster
  replicas: 2
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ionoscloudcluster
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: ionoscloudcluster-md-0
      clusterName: ionoscloudcluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: IONOSCloudMachineTemplate
        name: ionoscloudcluster-worker
      version: "1.25.11"
